name: hydeath
version: '${version}'
main: xyz.hynse.hydeath.Hydeath
api-version: '1.20'
authors: [MidnightTale]
website: hynse.xyz
folia-supported: true
commands:
  hydeathreload:
    description: Reloads the Hydeath configuration
    usage: /hydeathreload